<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
    	<a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" class="btn btn-primary btn-xs pull-right">Create New Post</a>
	  	<tr>
		    <th>Id</th>
		    <th>Name</th>
		    <th>Store ID</th>
		    <!-- <th>Image</th> -->
		    <th>Email</th>
		    <th>Passwordhash</th>
		 <!--    <th>Creared At</th>
		    <th>Updated At</th> -->
		    <th></th>
		    <th></th>
	    </tr>
    </thead>
    <?php
    $posts = $block->getPosts();
    foreach ($posts as $post) {
    	echo "<tr style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">";
    	echo "<td>".$post->getId()."</td>";
    	echo "<td>".$post->getName()."</td>";
    	echo "<td>".$post->getStoreId()."</td>";
    	// echo "<td>".$post->getImage()."</td>";
    	echo "<td>".$post->getEmail()."</td>";
        echo "<td>".$post->getPasswordHash()."</td>";
    
    	echo "<td>".$post->getCreatedAt()."</td>";
    	echo "<td>".$post->getUpdatedAt()."</td>";
    	echo "<td><a href='".$block->getBaseUrl()."blog/index/edit?post_id=".$post->getId()."'>Edit</a></td>";
    	echo "<td><a href='".$block->getBaseUrl()."blog/index/delete?post_id=".$post->getId()."'>Delete</a></td>";
    	echo "</tr>";
    }
    ?>
</table>